In [31]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.cluster import DBSCAN
from sklearn import preprocessing
import matplotlib.pyplot as plt
from sklearn.cluster import AgglomerativeClustering


In [21]:
data=pd.read_csv(r'C:\Users\Ghalamkarian\PycharmProjects\pythonProject3\clustring project.csv')

In [22]:
data.head()

CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [23]:
xx=data['Gender']
le=LabelEncoder()
encoder=le.fit_transform(xx)
data['Gender']=encoder

In [24]:
data.head()

CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1       1   19                  15                      39
1           2       1   21                  15                      81
2           3       0   20                  16                       6
3           4       0   23                  16                      77
4           5       0   31                  17                      40

In [25]:
data=data.drop('CustomerID',axis=1)
data.head()

Gender  Age  Annual Income (k$)  Spending Score (1-100)
0       1   19                  15                      39
1       1   21                  15                      81
2       0   20                  16                       6
3       0   23                  16                      77
4       0   31                  17                      40

In [26]:
data.isnull().sum()

Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

In [27]:
data.dtypes

Gender                    int32
Age                       int64
Annual Income (k$)        int64
Spending Score (1-100)    int64
dtype: object

In [28]:
w=data.columns
x=data[w]
x

Gender  Age  Annual Income (k$)  Spending Score (1-100)
0         1   19                  15                      39
1         1   21                  15                      81
2         0   20                  16                       6
3         0   23                  16                      77
4         0   31                  17                      40
..      ...  ...                 ...                     ...
195       0   35                 120                      79
196       0   45                 126                      28
197       1   32                 126                      74
198       1   32                 137                      18
199       1   30                 137                      83

[200 rows x 4 columns]

In [33]:
scalearn=preprocessing.StandardScaler()
xn=scalearn.fit(x).transform(x)
xn

array([[ 1.12815215, -1.42456879, -1.73899919, -0.43480148],
       [ 1.12815215, -1.28103541, -1.73899919,  1.19570407],
       [-0.88640526, -1.3528021 , -1.70082976, -1.71591298],
       [-0.88640526, -1.13750203, -1.70082976,  1.04041783],
       [-0.88640526, -0.56336851, -1.66266033, -0.39597992],
       [-0.88640526, -1.20926872, -1.66266033,  1.00159627],
       [-0.88640526, -0.27630176, -1.62449091, -1.71591298],
       [-0.88640526, -1.13750203, -1.62449091,  1.70038436],
       [ 1.12815215,  1.80493225, -1.58632148, -1.83237767],
       [-0.88640526, -0.6351352 , -1.58632148,  0.84631002],
       [ 1.12815215,  2.02023231, -1.58632148, -1.4053405 ],
       [-0.88640526, -0.27630176, -1.58632148,  1.89449216],
       [-0.88640526,  1.37433211, -1.54815205, -1.36651894],
       [-0.88640526, -1.06573534, -1.54815205,  1.04041783],
       [ 1.12815215, -0.13276838, -1.54815205, -1.44416206],
       [ 1.12815215, -1.20926872, -1.54815205,  1.11806095],
       [-0.88640526, -0.

In [43]:
from sklearn.cluster import KMeans
algorithms= {'DBSCAN':DBSCAN(eps=0.8,min_samples=8),
          'KMeans':KMeans(init= 'k-means++' ,n_clusters=5,n_init=12),
            'AgglomerativeClustering':AgglomerativeClustering(n_clusters=6,linkage='complete')}

In [44]:
for h in algorithms:
    v=algorithms[h].fit(xn)
    labels=v.labels_
    customer_cluster=set(labels)
    print(h,labels,customer_cluster)
    

DBSCAN [-1 -1 -1  0 -1  0 -1  0 -1  0 -1 -1 -1  0 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
  0 -1  0 -1  0  0 -1  0 -1 -1  0  0  0  0  0  0  0 -1  1  0  0  0  0  0
  0  0  0  2  0  1  0  1  0  1  0  1  1  2  0  0  1  2  0  0  2  0  1  0
  0  0  1  2  0  1  0  0  1  1  1  0  0  1  0  0  0  0  0  2  1  0  0  2
  0  0  1  2  0  0  1  2  1  0  0  1  1  1  1  0  0  2  0  0  0  0  0  0
  2  0  0  3  0  0  1  3 -1  3  4  3  0  0 -1  0 -1  3 -1  0 -1  3  0  0
 -1  3  1  0 -1  3  4  3 -1  0 -1  0  4  0 -1  0  0  0 -1  0  4  0  4  0
 -1  3  4  3  4  3 -1  0 -1  3 -1  3 -1  0  4  0 -1  3 -1 -1 -1  0 -1  0
 -1  0 -1  0 -1 -1 -1 -1] {0, 1, 2, 3, 4, -1}


C:\Users\Ghalamkarian\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1446: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


KMeans [0 0 1 2 1 2 1 2 4 2 4 2 1 2 4 0 1 0 4 2 4 0 1 0 1 0 1 0 1 2 4 2 4 0 1 2 1
 2 1 2 1 0 4 2 1 2 1 2 2 1 1 0 2 4 1 4 1 4 2 4 4 0 1 1 4 0 1 1 0 2 4 1 1 1
 4 0 1 4 2 1 4 0 4 1 2 4 1 2 2 1 1 0 4 1 2 0 1 2 4 0 2 1 4 0 4 2 1 4 4 4 4
 2 1 0 2 2 1 1 1 1 0 1 2 0 2 2 4 0 4 0 4 0 2 2 3 2 3 0 3 2 3 0 2 2 3 0 4 2
 3 0 3 0 3 2 3 2 3 2 3 2 1 2 3 2 4 2 3 2 3 0 3 0 3 0 3 2 4 0 4 0 3 2 3 2 3
 0 3 0 3 2 3 2 3 2 3 2 3 0 3 0] {0, 1, 2, 3, 4}
AgglomerativeClustering [4 0 4 0 4 0 4 0 5 0 5 0 2 0 4 0 4 0 5 0 4 0 2 0 2 0 2 0 2 0 5 0 5 0 2 0 2
 0 2 0 2 0 5 4 2 0 2 4 4 4 2 0 4 5 2 5 2 5 4 5 5 0 2 2 5 0 2 2 0 4 5 2 2 2
 5 0 2 0 4 2 5 0 5 2 4 5 2 4 4 2 2 0 5 4 4 0 2 4 5 0 4 2 5 0 5 4 2 5 5 5 5
 4 4 0 4 4 2 2 2 2 0 4 4 3 4 3 5 3 1 3 1 3 4 3 1 3 1 3 1 3 2 3 4 3 1 3 5 3
 1 3 1 3 1 3 1 3 1 3 1 3 2 3 1 3 1 3 1 3 1 3 1 3 1 3 2 3 1 3 1 3 1 3 1 3 1
 3 2 3 1 3 1 3 1 3 1 3 1 3 1 3] {0, 1, 2, 3, 4, 5}


In [11]:
db=DBSCAN(eps=0.8,min_samples=8).fit(x)
labels=db.labels_
labels

array([-1, -1, -1,  0, -1,  0, -1,  0, -1,  0, -1, -1, -1,  0, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1,  0, -1,  0, -1,  0,  0, -1,  0, -1, -1,
        0,  0,  0,  0,  0,  0,  0, -1,  1,  0,  0,  0,  0,  0,  0,  0,  0,
        2,  0,  1,  0,  1,  0,  1,  0,  1,  1,  2,  0,  0,  1,  2,  0,  0,
        2,  0,  1,  0,  0,  0,  1,  2,  0,  1,  0,  0,  1,  1,  1,  0,  0,
        1,  0,  0,  0,  0,  0,  2,  1,  0,  0,  2,  0,  0,  1,  2,  0,  0,
        1,  2,  1,  0,  0,  1,  1,  1,  1,  0,  0,  2,  0,  0,  0,  0,  0,
        0,  2,  0,  0,  3,  0,  0,  1,  3, -1,  3,  4,  3,  0,  0, -1,  0,
       -1,  3, -1,  0, -1,  3,  0,  0, -1,  3,  1,  0, -1,  3,  4,  3, -1,
        0, -1,  0,  4,  0, -1,  0,  0,  0, -1,  0,  4,  0,  4,  0, -1,  3,
        4,  3,  4,  3, -1,  0, -1,  3, -1,  3, -1,  0,  4,  0, -1,  3, -1,
       -1, -1,  0, -1,  0, -1,  0, -1,  0, -1, -1, -1, -1], dtype=int64)

In [12]:
data['labels']=labels
data.head()

Gender  Age  Annual Income (k$)  Spending Score (1-100)  labels
0       1   19                  15                      39      -1
1       1   21                  15                      81      -1
2       0   20                  16                       6      -1
3       0   23                  16                      77       0
4       0   31                  17                      40      -1

In [13]:
set(labels)

{-1, 0, 1, 2, 3, 4}

In [14]:
data['labels'].value_counts()

labels
 0    90
-1    52
 1    24
 3    15
 2    11
 4     8
Name: count, dtype: int64

In [15]:
f=db.core_sample_indices_
f
#####

array([  3,   5,  13,  29,  31,  35,  37,  39,  43,  44,  45,  46,  47,
        48,  49,  50,  52,  54,  56,  58,  59,  60,  61,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  78,  79,
        80,  82,  83,  84,  85,  86,  87,  88,  89,  92,  93,  94,  95,
        96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 107, 108, 109,
       110, 111, 112, 113, 114, 115, 117, 118, 119, 121, 122, 123, 125,
       127, 132, 133, 135, 137, 139, 141, 142, 143, 147, 149, 150, 151,
       153, 155, 157, 159, 161, 163, 165, 167, 173, 175, 181, 183, 189],
      dtype=int64)

In [16]:
n_clusters_ = len(set(labels)) - (1 if -1 in labels else 0)
print(n_clusters_ )
n_noise_ = list(labels).count(-1)
print(n_noise_)

5
52


K_MEAN

In [17]:
from sklearn.cluster import KMeans

In [18]:
kmean=KMeans(init= 'k-means++' ,n_clusters=5,n_init=12)
kmean.fit(x)


C:\Users\Ghalamkarian\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1436: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


KMeans(n_clusters=5, n_init=12)

In [19]:
labelss=kmean.labels_
labelss[:10]

array([3, 3, 2, 1, 2, 1, 2, 1, 0, 1])

In [20]:
cluster_center=kmean.cluster_centers_
cluster_center

array([[ 1.12815215,  1.20414253, -0.29510422, -0.54350185],
       [-0.88640526, -0.75047453, -0.00501655,  0.6979562 ],
       [-0.88640526,  0.7517978 , -0.51757746, -0.4420241 ],
       [ 1.12815215, -0.76072691,  0.05496398,  0.83369302],
       [ 0.12087344, -0.07756323,  1.17949408, -1.32321797]])

In [21]:
data['kmean']=labelss
data.head()

Gender  Age  Annual Income (k$)  Spending Score (1-100)  labels  kmean
0       1   19                  15                      39      -1      3
1       1   21                  15                      81      -1      3
2       0   20                  16                       6      -1      2
3       0   23                  16                      77       0      1
4       0   31                  17                      40      -1      2

In [28]:
data=data.drop('labels',axis=1)

In [29]:
data['kmean'].value_counts()

kmean
1    56
2    43
3    40
0    35
4    26
Name: count, dtype: int64

In [30]:
data.groupby('kmean').mean()

Gender        Age  Annual Income (k$)  Spending Score (1-100)
kmean                                                               
0         1.0  55.628571           52.828571               36.200000
1         0.0  28.392857           60.428571               68.178571
2         0.0  49.325581           47.000000               38.813953
3         1.0  28.250000           62.000000               71.675000
4         0.5  37.769231           91.461538               16.115385

agglomarative

In [31]:
xxx=data[['Gender','Age','Annual Income (k$)','Spending Score (1-100)']]

In [32]:
from sklearn.preprocessing import MinMaxScaler
xo=xxx.values
scaler=MinMaxScaler()
normaldata=scaler.fit_transform(xo)
normaldata[0:5]

array([[1.        , 0.01923077, 0.        , 0.3877551 ],
       [1.        , 0.05769231, 0.        , 0.81632653],
       [0.        , 0.03846154, 0.00819672, 0.05102041],
       [0.        , 0.09615385, 0.00819672, 0.7755102 ],
       [0.        , 0.25      , 0.01639344, 0.39795918]])

In [33]:
from sklearn.metrics.pairwise import euclidean_distances
dis=euclidean_distances(normaldata, normaldata)
print(dis[:5])

[[0.         0.43029381 1.05538015 1.07533175 1.02646349 1.07058018
  1.09939505 1.14956286 0.94069617 1.07666789 0.95823955 1.21268023
  1.27442327 1.07762667 0.43805191 0.41425271 1.04821717 0.28052522
  0.64610288 1.20889521 0.31903388 0.3729909  1.18181459 0.42466407
  1.23671503 0.49077558 1.1253695  0.39550562 1.08762315 1.12204532
  0.87426513 1.06628453 0.75949599 0.56091039 1.19150561 1.09859961
  1.12706965 1.09058208 1.0756364  1.08066264 1.34898179 0.58074898
  0.59216306 1.06880746 1.17649413 1.05751226 1.19333414 1.03553075
  1.03918755 1.04698756 1.18296908 0.40912387 1.06271171 0.83084797
  1.1882011  0.58568877 1.20324593 0.99305684 1.05034678 0.70511191
  1.02789391 0.30202903 1.39228824 1.25039217 0.89673625 0.33938908
  1.13964138 1.40340429 0.33884381 1.06879825 1.03258469 1.16984838
  1.30934605 1.31683954 0.83700068 0.37912968 1.17157946 0.52317872
  1.06099211 1.19831866 0.80697441 0.51220284 0.97707613 1.17234549
  1.06649215 0.64677123 1.27882562 1.07168115 1.

In [66]:
from sklearn.cluster import AgglomerativeClustering

agglom=AgglomerativeClustering(n_clusters=6,linkage='complete')
rr=agglom.fit(dis)

C:\Users\Ghalamkarian\anaconda3\Lib\site-packages\sklearn\cluster\_agglomerative.py:566: ClusterWarning: scipy.cluster: The symmetric non-negative hollow observation matrix looks suspiciously like an uncondensed distance matrix
  out = hierarchy.linkage(X, method=linkage, metric=affinity)


In [67]:
agglom.labels_

array([1, 1, 3, 5, 2, 5, 3, 5, 0, 5, 0, 5, 3, 5, 4, 1, 2, 1, 0, 5, 4, 1,
       3, 1, 3, 1, 2, 4, 2, 5, 0, 5, 0, 1, 3, 5, 2, 5, 2, 5, 3, 1, 4, 2,
       2, 5, 2, 2, 2, 2, 2, 4, 2, 0, 2, 4, 2, 0, 2, 0, 0, 1, 3, 2, 0, 1,
       2, 3, 1, 2, 0, 2, 3, 3, 0, 1, 2, 4, 2, 2, 0, 4, 0, 2, 2, 4, 2, 2,
       2, 2, 3, 1, 4, 2, 2, 1, 2, 2, 4, 1, 2, 2, 0, 1, 4, 2, 3, 0, 0, 0,
       0, 2, 2, 1, 2, 2, 3, 2, 2, 2, 1, 2, 2, 1, 2, 2, 4, 1, 0, 1, 0, 1,
       2, 2, 0, 5, 3, 1, 0, 2, 3, 1, 2, 5, 0, 1, 4, 2, 3, 1, 0, 1, 3, 2,
       3, 5, 0, 2, 0, 2, 3, 5, 0, 5, 0, 2, 0, 5, 3, 1, 0, 1, 0, 1, 3, 5,
       0, 1, 0, 1, 3, 5, 0, 5, 3, 1, 3, 1, 3, 5, 3, 5, 0, 5, 3, 5, 3, 1,
       0, 1], dtype=int64)

In [68]:
data['cluster']=agglom.labels_

In [69]:
data.head()

Gender  Age  Annual Income (k$)  Spending Score (1-100)  kmean  cluster
0       1   19                  15                      39      3        1
1       1   21                  15                      81      3        1
2       0   20                  16                       6      2        3
3       0   23                  16                      77      1        5
4       0   31                  17                      40      2        2

In [70]:
data.value_counts(data['cluster'])

cluster
2    57
0    37
1    37
3    29
5    26
4    14
Name: count, dtype: int64